name: Feature Request
description: Suggest an idea for this project.
title: "Feature Request: "
labels: "enhancement"
assignees: ''

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you are suggesting.
      placeholder: Describe the feature you are suggesting.
    validations:
      required: true
  - type: textarea
    id: feature-implementation
    attributes:
      label: Possible Implementation
      description: Describe how you think this feature could be implemented.
      placeholder: Describe possible implementations.
      value: ''
    validations:
      required: true
  - type: textarea
    id: feature-alternatives
    attributes:
      label: Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe alternative solutions considered.
      value: ''
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false