name: Validate Terraform

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.3

      - name: Check format
        run: terraform fmt -check -recursive

      - name: Init
        run: terraform -chdir=infrastructure init -backend=false

      - name: Validate
        run: terraform -chdir=infrastructure validate -no-color
